import pandas as pd

# Load the WHR dataset
whr_data = pd.read_csv("hapiscore_whr.csv")

# Extract relevant information (e.g., country name and happiness score in 2022)
country_scores = whr_data[['country', '2022']]

# Print happiness score of a specific country
print(country_scores[country_scores['country'] == 'Afghanistan'])
print(country_scores[country_scores['country'] == 'Angola'])
print(country_scores[country_scores['country'] == 'Albania'])
print(country_scores[country_scores['country'] == 'United Arab Emirates'])
print(country_scores[country_scores['country'] == 'Argentina'])
print(country_scores[country_scores['country'] == 'Armenia'])
print(country_scores[country_scores['country'] == 'Australia'])
print(country_scores[country_scores['country'] == 'Austria'])
print(country_scores[country_scores['country'] == 'Azerbaijan'])
print(country_scores[country_scores['country'] == 'Burundi'])
print(country_scores[country_scores['country'] == 'Belgium'])
print(country_scores[country_scores['country'] == 'Benin'])
print(country_scores[country_scores['country'] == 'Burkina Faso'])
print(country_scores[country_scores['country'] == 'Bangladesh'])
print(country_scores[country_scores['country'] == 'Bulgaria'])
print(country_scores[country_scores['country'] == 'Bahrain'])
print(country_scores[country_scores['country'] == 'Bosnia and Herzegovina'])
print(country_scores[country_scores['country'] == 'Belarus'])
print(country_scores[country_scores['country'] == 'Bulgaria'])
print(country_scores[country_scores['country'] == 'Belize'])
print(country_scores[country_scores['country'] == 'Bolivia'])
print(country_scores[country_scores['country'] == 'Brazil'])
print(country_scores[country_scores['country'] == 'Bhutan'])
print(country_scores[country_scores['country'] == 'Botswana'])
print(country_scores[country_scores['country'] == 'Central African Republic'])
print(country_scores[country_scores['country'] == 'Canada'])
print(country_scores[country_scores['country'] == 'Switzerland'])
print(country_scores[country_scores['country'] == 'Chile'])
print(country_scores[country_scores['country'] == 'China'])
print(country_scores[country_scores['country'] == "Cote d'Ivoire"])
print(country_scores[country_scores['country'] == 'Cameroon'])
print(country_scores[country_scores['country'] == 'Congo, Dem. Rep.'])
print(country_scores[country_scores['country'] == 'Congo, Rep.'])
print(country_scores[country_scores['country'] == 'Colombia'])
print(country_scores[country_scores['country'] == 'Comoros'])
print(country_scores[country_scores['country'] == 'Costa Rica'])
print(country_scores[country_scores['country'] == 'Cuba'])
print(country_scores[country_scores['country'] == 'Cyprus'])
print(country_scores[country_scores['country'] == 'Czech Republic'])
print(country_scores[country_scores['country'] == 'Germany'])
print(country_scores[country_scores['country'] == 'Djibouti'])
print(country_scores[country_scores['country'] == 'Denmark'])
print(country_scores[country_scores['country'] == 'Dominican Republic'])
print(country_scores[country_scores['country'] == 'Algeria'])
print(country_scores[country_scores['country'] == 'Ecuador'])
print(country_scores[country_scores['country'] == 'Egypt'])
print(country_scores[country_scores['country'] == 'Spain'])
print(country_scores[country_scores['country'] == 'Estonia'])
print(country_scores[country_scores['country'] == 'Ethiopia'])
print(country_scores[country_scores['country'] == 'Finland'])
print(country_scores[country_scores['country'] == 'France'])
print(country_scores[country_scores['country'] == 'Gabon'])
print(country_scores[country_scores['country'] == 'UK'])
print(country_scores[country_scores['country'] == 'Georgia'])
print(country_scores[country_scores['country'] == 'Ghana'])
print(country_scores[country_scores['country'] == 'Guinea'])
print(country_scores[country_scores['country'] == 'Gambia'])
print(country_scores[country_scores['country'] == 'Greece'])
print(country_scores[country_scores['country'] == 'Guatemala'])
print(country_scores[country_scores['country'] == 'Guyana'])
print(country_scores[country_scores['country'] == 'Hong Kong, China'])
print(country_scores[country_scores['country'] == 'Honduras'])
print(country_scores[country_scores['country'] == 'Croatia'])
print(country_scores[country_scores['country'] == 'Haiti'])
print(country_scores[country_scores['country'] == 'Hungary'])
print(country_scores[country_scores['country'] == 'Indonesia'])
print(country_scores[country_scores['country'] == 'India'])
print(country_scores[country_scores['country'] == 'Ireland'])
print(country_scores[country_scores['country'] == 'Iran'])
print(country_scores[country_scores['country'] == 'Iraq'])
print(country_scores[country_scores['country'] == 'Iceland'])
print(country_scores[country_scores['country'] == 'Israel'])
print(country_scores[country_scores['country'] == 'Italy'])
print(country_scores[country_scores['country'] == 'Jamaica'])
print(country_scores[country_scores['country'] == 'Jordan'])
print(country_scores[country_scores['country'] == 'Japan'])
print(country_scores[country_scores['country'] == 'Kazakhstan'])
print(country_scores[country_scores['country'] == 'Kenya'])
print(country_scores[country_scores['country'] == 'Kyrgyz Republic'])
print(country_scores[country_scores['country'] == 'Cambodia'])
print(country_scores[country_scores['country'] == 'South Korea'])
print(country_scores[country_scores['country'] == 'Kuwait'])
print(country_scores[country_scores['country'] == 'Lao'])
print(country_scores[country_scores['country'] == 'Lebanon'])
print(country_scores[country_scores['country'] == 'Liberia'])
print(country_scores[country_scores['country'] == 'Libya'])
print(country_scores[country_scores['country'] == 'Sri Lanka'])
print(country_scores[country_scores['country'] == 'Lesotho'])
print(country_scores[country_scores['country'] == 'Lithuania'])
print(country_scores[country_scores['country'] == 'Luxembourg'])
print(country_scores[country_scores['country'] == 'Latvia'])
print(country_scores[country_scores['country'] == 'Morocco'])
print(country_scores[country_scores['country'] == 'Moldova'])
print(country_scores[country_scores['country'] == 'Madagascar'])
print(country_scores[country_scores['country'] == 'Maldives'])
print(country_scores[country_scores['country'] == 'Mexico'])
print(country_scores[country_scores['country'] == 'North Macedonia'])
print(country_scores[country_scores['country'] == 'Mali'])
print(country_scores[country_scores['country'] == 'Malta'])
print(country_scores[country_scores['country'] == 'Myanmar'])
print(country_scores[country_scores['country'] == 'Montenegro'])
print(country_scores[country_scores['country'] == 'Mongolia'])
print(country_scores[country_scores['country'] == 'Mozambique'])
print(country_scores[country_scores['country'] == 'Mauritania'])
print(country_scores[country_scores['country'] == 'Mauritius'])
print(country_scores[country_scores['country'] == 'Malawi'])
print(country_scores[country_scores['country'] == 'Malaysia'])
print(country_scores[country_scores['country'] == 'Namibia'])
print(country_scores[country_scores['country'] == 'Niger'])
print(country_scores[country_scores['country'] == 'Nigeria'])
print(country_scores[country_scores['country'] == 'Nicaragua'])
print(country_scores[country_scores['country'] == 'Netherlands'])
print(country_scores[country_scores['country'] == 'Norway'])
print(country_scores[country_scores['country'] == 'Nepal'])
print(country_scores[country_scores['country'] == 'New Zealand'])
print(country_scores[country_scores['country'] == 'Oman'])
print(country_scores[country_scores['country'] == 'Pakistan'])
print(country_scores[country_scores['country'] == 'Panama'])
print(country_scores[country_scores['country'] == 'Peru'])
print(country_scores[country_scores['country'] == 'Philippines'])
print(country_scores[country_scores['country'] == 'Poland'])
print(country_scores[country_scores['country'] == 'Portugal'])
print(country_scores[country_scores['country'] == 'Paraguay'])
print(country_scores[country_scores['country'] == 'Palestine'])
print(country_scores[country_scores['country'] == 'Qatar'])
print(country_scores[country_scores['country'] == 'Romania'])
print(country_scores[country_scores['country'] == 'Russia'])
print(country_scores[country_scores['country'] == 'Rwanda'])
print(country_scores[country_scores['country'] == 'Saudi Arabia'])
print(country_scores[country_scores['country'] == 'Sudan'])
print(country_scores[country_scores['country'] == 'Senegal'])
print(country_scores[country_scores['country'] == 'Singapore'])
print(country_scores[country_scores['country'] == 'Sierra Leone'])
print(country_scores[country_scores['country'] == 'El Salvador'])
print(country_scores[country_scores['country'] == 'Somalia'])
print(country_scores[country_scores['country'] == 'Serbia'])
print(country_scores[country_scores['country'] == 'South Sudan'])
print(country_scores[country_scores['country'] == 'Suriname'])
print(country_scores[country_scores['country'] == 'Slovak Republic'])
print(country_scores[country_scores['country'] == 'Slovenia'])
print(country_scores[country_scores['country'] == 'Sweden'])
print(country_scores[country_scores['country'] == 'Eswatini'])
print(country_scores[country_scores['country'] == 'Syria'])
print(country_scores[country_scores['country'] == 'Chad'])
print(country_scores[country_scores['country'] == 'Togo'])
print(country_scores[country_scores['country'] == 'Thailand'])
print(country_scores[country_scores['country'] == 'Tajikistan'])
print(country_scores[country_scores['country'] == 'Turkmenistan'])
print(country_scores[country_scores['country'] == 'Trinidad and Tobago'])
print(country_scores[country_scores['country'] == 'Tunisia'])
print(country_scores[country_scores['country'] == 'Turkey'])
print(country_scores[country_scores['country'] == 'Taiwan'])
print(country_scores[country_scores['country'] == 'Tanzania'])
print(country_scores[country_scores['country'] == 'Uganda'])
print(country_scores[country_scores['country'] == 'Ukraine'])
print(country_scores[country_scores['country'] == 'Uruguay'])
print(country_scores[country_scores['country'] == 'USA'])
print(country_scores[country_scores['country'] == 'Uzbekistan'])
print(country_scores[country_scores['country'] == 'Venezuela'])
print(country_scores[country_scores['country'] == 'Vietnam'])
print(country_scores[country_scores['country'] == 'Yemen'])
print(country_scores[country_scores['country'] == 'South Africa'])
print(country_scores[country_scores['country'] == 'Zambia'])
print(country_scores[country_scores['country'] == 'Zimbabwe'])

